jwt:
  secret-key: d2VyaW5zd2VpbnN1cGVyd2FzZ2Vpc2VjcmV0a2V5Zm9yand0YW5kc3ByaW5n
  access-token:
    expiration: 1800
  refresh-token:
    expiration: 604800

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authDB
    username: postgres
    password: Tim4ik13