jwt:
  secret-key: d2VyaW5zd2VpbnN1cGVyd2FzZ2Vpc2VjcmV0a2V5Zm9yand0YW5kc3ByaW5n
  access-token:
    # in millis
    expiration: 1800000
  refresh-token:
    # in millis
    expiration: 604800000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/authDB
    username: postgres
    password: Timofey1305