jwt:
  secret-key: ${JWT_SECRET}
  access-token:
    # in millis
    expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refresh-token:
    # in millis
    expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}